# Generated by Django 2.1.2 on 2018-10-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilteringMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Mooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.PositiveIntegerField()),
                ('explanation_variable', models.CharField(blank=True, max_length=512, null=True)),
                ('filtering_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis_app.FilteringMethod')),
            ],
        ),
    ]
