# Generated by Django 2.1.2 on 2018-10-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('add_to_version_set', models.BooleanField(default=False)),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axis_app.Mooclet')),
            ],
        ),
    ]
