# Generated by Django 2.1.2 on 2018-10-09 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0002_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='added_to_version_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explanation',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
