# Generated by Django 2.1.2 on 2018-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0003_auto_20181009_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
