# Generated by Django 2.1.2 on 2018-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0005_auto_20181009_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mooclet',
            old_name='engine_id',
            new_name='input_engine_id',
        ),
        migrations.AddField(
            model_name='mooclet',
            name='input_engine_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mooclet',
            name='output_engine_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mooclet',
            name='output_engine_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
