# Generated by Django 2.1.2 on 2018-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0006_auto_20181016_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooclet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
